### ISSUE TITLE
When building for Android, there is an error.

### ISSUE THREAD

**Issue by scotttball** [Plotprojects/plotprojects-react-native-module#1]
I'm running React Native 0.64.3, node 12.21.0, and the latest of this package. It seems like the package is working with iOS, but when I try to run Android, this is the error that I'm getting.

<img width="2112" alt="Screen Shot 2021-03-02 at 8 48 34 PM" src="https://user-images.githubusercontent.com/14366492/109749911-b9f4b680-7b98-11eb-8194-6067d32f6c95.png">

**Comment by yahya-plotprojects** [comment]
@scotttball Thanks for contacting us.
We have published a new version of our plugin. I hope that would resolve your issue.
