### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by ToniLloyds** [Plotprojects/plotprojects-react-native-module#3]
Step 2 of the readme says:
```
Add plotconfig.json file to both Android and iOS projects 
Here you can find instruction for iOS and Android.
```
But the links are broken
https://github.com/Plotprojects/plotprojects-react-native-module/blob/HEAD/iOS-integration-guide.md#step-4-add-configuration-file

Also on the official website link to IOS setup is broken
http://files.plotprojects.com/documentation/ios/reference/iOS-integration-guide.md#step-4-add-configuration-file

**Comment by marshall20** [comment]
Hi Toni,

Thanks for reporting the issue, we will update the links.

You need to add the config files to this path:

ios/Supporting Files/plotconfig.json
android/app/src/main/assets/plotconfig.json

Hope this helps

**Comment by ToniLloyds** [comment]
Yes it does help. Thanks.

Also code on step 3 is wrong
http://files.plotprojects.com/documentation/android/3.13.0/how-to-guides/React-Native-integration-guide/

Instead of 
`import PermissionsAndroid from 'react-native';`

It should be:
`import { PermissionsAndroid } from 'react-native';`

**Comment by yahya-plotprojects** [comment]
React native related documentation is now moved to the README.md file instead of general documentation
