### ISSUE TITLE
registerGeotriggerHandler is not a function

### ISSUE THREAD

**Issue by ToniLloyds** [Plotprojects/plotprojects-react-native-module#4]
After successfully installing a package i was able to get Plot module.

However method `registerGeotriggerHandler` doesnt exist there.

Example:

```
 const Plot = NativeModules.PlotProjectsReactModule;
 
  Plot.registerGeotriggerHandler((batchId, geotriggers) => { <-- This throws an error
    //doSomething
  });
```

**Comment by yahya-plotprojects** [comment]
Hi Toni,

Thank you for reporting this issue. Can you try again with the latest version 1.0.7?
Please note that you need to import Plot module using the following:

```
import Plot from 'plotprojects-react-native-module';
``` 

instead of

```
const Plot = NativeModules.PlotProjectsReactModule;
```

**Comment by yahya-plotprojects** [comment]
@ToniLloyds are you still experiencing this issue or can I close it already?
