### ISSUE TITLE
Android registerNotificationOpenHandler error

### ISSUE THREAD

**Issue by ElenaMironovaA** [Plotprojects/plotprojects-react-native-module#8]
Hello!

when I call `Plot.registerNotificationOpenHandler`, I get error `java.lang.double cannot be cast to java.lang.string`

<img width="440" alt="image" src="https://user-images.githubusercontent.com/108752263/203364370-83680f42-ec26-43cb-981e-901ac1029cba.png">

could you take a look?

**Comment by YahyaAlfayad** [comment]
Hello Elena,

I am looking into this now. Will keep you up to date about this.

**Comment by YahyaAlfayad** [comment]
I've deployed a new version today with few improvements around the notification open handler. Please let me know if you are still having issues with the new version.

**Comment by ElenaMironovaA** [comment]
Thank you! i will check it and let you know!

**Comment by ElenaMironovaA** [comment]
Hi Yahya!

Unfortunately this issue still produced...
I call only `Plot.registerNotificationOpenHandler` but according to logs this method called twice

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/108752263/205950519-752bac2e-a761-4b72-b63d-0759dd218668.png">

**Comment by YahyaAlfayad** [comment]
Hi Elena,

I am really struggling to reproduce the conversion error. I am testing with the example app from https://github.com/Plotprojects/plot-react-native-module-example but can't get that error.

Do you get the same error if you test with that example app? If so, do you get it right after the registration or after clicking on the notification?

Regarding the multiple calls of registering a handler, unfortunately this is a react native specific behaviour. However with every call it makes sure automatically to remove the previously registered handler so it should be fine.

**Comment by ElenaMironovaA** [comment]
Hi!

I run this project and all work fine.
I updated in my project "metro-react-native-babel-preset" "0.68.0" -> "0.70.3" and it solved my problem!

**Comment by YahyaAlfayad** [comment]
I am glad to hear that. I will close this issue now.
